### ISSUE TITLE
Getting a "not found" error after install

### ISSUE THREAD

**Issue by simonwjackson** [juampi92/hexo-tag-googlecharts#1]
``` bash
$ npm install hexo-tag-googlecharts --save
```

``` bash
$hexo server --drafts

Template render error: unknown block tag: googlecharts
    at Error.exports.TemplateError (/home/simonwjackson/src/niche/miniarray.com/node_modules/hexo/node_modules/nunjucks/src/lib.js:51:19)
    at Object.extend.fail (/home/simonwjackson/src/niche/miniarray.com/node_modules/hexo/node_modules/nunjucks/src/parser.js:64:15)
    at Object.extend.parseStatement (/home/simonwjackson/src/niche/miniarray.com/node_modules/hexo/node_modules/nunjucks/src/parser.js:544:18)
    at Object.extend.parseNodes (/home/simonwjackson/src/niche/miniarray.com/node_modules/hexo/node_modules/nunjucks/src/parser.js:1151:30)
    at Object.extend.parseAsRoot (/home/simonwjackson/src/niche/miniarray.com/node_modules/hexo/node_modules/nunjucks/src/parser.js:1177:42)
    at Object.module.exports.parse (/home/simonwjackson/src/niche/miniarray.com/node_modules/hexo/node_modules/nunjucks/src/parser.js:1199:18)
    at Object.module.exports.compile (/home/simonwjackson/src/niche/miniarray.com/node_modules/hexo/node_modules/nunjucks/src/compiler.js:1118:48)
    at Obj.extend._compile (/home/simonwjackson/src/niche/miniarray.com/node_modules/hexo/node_modules/nunjucks/src/environment.js:444:35)
    at Obj.extend.compile (/home/simonwjackson/src/niche/miniarray.com/node_modules/hexo/node_modules/nunjucks/src/environment.js:433:18)
    at null.<anonymous> (/home/simonwjackson/src/niche/miniarray.com/node_modules/hexo/node_modules/nunjucks/src/environment.js:378:22)
    at Object.exports.withPrettyErrors (/home/simonwjackson/src/niche/miniarray.com/node_modules/hexo/node_modules/nunjucks/src/lib.js:24:16)
    at Obj.extend.render (/home/simonwjackson/src/niche/miniarray.com/node_modules/hexo/node_modules/nunjucks/src/environment.js:374:20)
    at Obj.extend.renderString (/home/simonwjackson/src/niche/miniarray.com/node_modules/hexo/node_modules/nunjucks/src/environment.js:261:21)
    at /home/simonwjackson/src/niche/miniarray.com/node_modules/hexo/lib/extend/tag.js:56:9
    at tryCatcher (/home/simonwjackson/src/niche/miniarray.com/node_modules/hexo/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._resolveFromResolver (/home/simonwjackson/src/niche/miniarray.com/node_modules/hexo/node_modules/bluebird/js/main/promise.js:476:31)
    at new Promise (/home/simonwjackson/src/niche/miniarray.com/node_modules/hexo/node_modules/bluebird/js/main/promise.js:69:37)
    at Tag.render (/home/simonwjackson/src/niche/miniarray.com/node_modules/hexo/lib/extend/tag.js:55:10)
    at Object.tagFilter [as onRenderEnd] (/home/simonwjackson/src/niche/miniarray.com/node_modules/hexo/lib/hexo/post.js:253:16)
    at /home/simonwjackson/src/niche/miniarray.com/node_modules/hexo/lib/hexo/render.js:55:19
    at tryCatcher (/home/simonwjackson/src/niche/miniarray.com/node_modules/hexo/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/simonwjackson/src/niche/miniarray.com/node_modules/hexo/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/home/simonwjackson/src/niche/miniarray.com/node_modules/hexo/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (/home/simonwjackson/src/niche/miniarray.com/node_modules/hexo/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/home/simonwjackson/src/niche/miniarray.com/node_modules/hexo/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/simonwjackson/src/niche/miniarray.com/node_modules/hexo/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/simonwjackson/src/niche/miniarray.com/node_modules/hexo/node_modules/bluebird/js/main/async.js:15:14)
```

``` bash
$hexo --version

hexo: 3.1.1
os: Linux 4.1.0-1-mainline linux x64
http_parser: 2.3
node: 0.12.7
v8: 3.28.71.19
uv: 1.6.1
zlib: 1.2.8
modules: 14
openssl: 1.0.2d
```

**Comment by simonwjackson** [comment]
Sorry, non issue
